const $=s=>document.querySelector(s);let cards=[],cardIndex=0,flipped=false,known=0,quizIndex=0,quizScore=0,answered=false,setId=null;
const user=JSON.parse(localStorage.getItem('gizmoUser')||'null');
async function studyApi(action,body={}){const r=await fetch('study.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||'Request failed');return d}
function parseCards(){return [...document.querySelectorAll('.card-row')].map(row=>({q:row.querySelector('.card-question').value.trim(),a:row.querySelector('.card-answer').value.trim()})).filter(card=>card.q&&card.a)}
function updateCount(){$('#cardCount').textContent=`${parseCards().length} card${parseCards().length===1?'':'s'} ready`}
function addCard(card={q:'',a:''}){const row=document.createElement('div');row.className='card-row';row.innerHTML='<label>Question<input class="card-question" maxlength="500" placeholder="e.g. What is photosynthesis?"></label><label>Answer<textarea class="card-answer" rows="2" maxlength="1000" placeholder="e.g. The process plants use to make food from light."></textarea></label><button class="remove-card" type="button" aria-label="Remove flashcard">×</button>';row.querySelector('.card-question').value=card.q||'';row.querySelector('.card-answer').value=card.a||'';row.querySelectorAll('input,textarea').forEach(input=>input.addEventListener('input',updateCount));row.querySelector('.remove-card').addEventListener('click',()=>{if(document.querySelectorAll('.card-row').length===1){row.querySelectorAll('input,textarea').forEach(input=>input.value='')}else{row.remove()}updateCount()});$('#cardsEditor').append(row);return row}
function setCardRows(newCards){$('#cardsEditor').innerHTML='';newCards.forEach(addCard);if(!newCards.length)addCard();updateCount()}
$('#addCard').addEventListener('click',()=>{const row=addCard();row.querySelector('.card-question').focus()});
setCardRows([{q:'',a:''},{q:'',a:''}]);
function showSource(source){const ai=source==='ai';$('#manualSource').classList.toggle('hidden',ai);$('#aiSource').classList.toggle('hidden',!ai);document.querySelectorAll('.source-option').forEach(b=>b.classList.toggle('active',b.dataset.source===source));$('#error').textContent=''}
document.querySelectorAll('.source-option').forEach(b=>b.addEventListener('click',async()=>{showSource(b.dataset.source);if(b.dataset.source!=='ai')return;try{const d=await studyApi('aiStatus');if(!d.configured){$('#error').innerHTML='No OpenAI key yet — cards will be drafted locally. <a href="setup_ai.php">Add OpenAI key</a> for smarter AI.'}}catch{}}));
function loadFile(file){if(!file)return;if(file.size>2*1024*1024){$('#error').textContent='Please choose a file smaller than 2 MB.';return}if(!/\.(txt|md|csv)$/i.test(file.name)){ $('#error').textContent='Use a TXT, Markdown, or CSV notes file.';return}const reader=new FileReader();reader.onload=()=>{$('#sourceText').value=String(reader.result||'');$('#fileName').textContent=file.name;$('#error').textContent=''};reader.onerror=()=>$('#error').textContent='Could not read that file.';reader.readAsText(file)}
$('#fileInput').addEventListener('change',e=>loadFile(e.target.files[0]));
const dropZone=$('#dropZone');['dragenter','dragover'].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.remove('dragging')}));dropZone.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
$('#generateCards').addEventListener('click',async()=>{const material=$('#sourceText').value.trim();if(material.length<30){$('#error').textContent='Add a little more study material first.';return}const button=$('#generateCards');button.disabled=true;button.innerHTML='Making cards…';$('#error').textContent='';try{const data=await studyApi('generateCards',{material,count:Number($('#aiCardCount').value)});const generated=(data.cards||[]).filter(c=>c&&c.q&&c.a);if(generated.length<2)throw new Error('Could not make enough usable cards. Try adding more detail.');setCardRows(generated);showSource('manual');const mode=data.mode==='openai'?'AI':'Local draft';$('#error').textContent=`${generated.length} ${mode} flashcards are ready to review.`+(data.message?` ${data.message}`:'')}catch(error){$('#error').textContent=error.message}finally{button.disabled=false;button.innerHTML='Generate cards <span>✦</span>'}});
$('#createSet').addEventListener('click',async()=>{cards=parseCards();if(cards.length<2){$('#error').textContent='Add at least two valid Question | Answer lines.';return}const title=$('#setTitle').value.trim()||'My study set';localStorage.setItem('gizmoStudySet',JSON.stringify({title,cards}));if(user?.id){try{const d=await studyApi('saveSet',{userId:user.id,title,cards});setId=d.setId}catch{}}$('#setName').textContent=title.toUpperCase();$('#builder').classList.add('hidden');$('#learn').classList.remove('hidden');cardIndex=0;known=0;renderCard()});
$('#exitSet').addEventListener('click',()=>location.href='index.html');
function renderCard(){flipped=false;const card=cards[cardIndex];$('#cardSide').textContent='QUESTION';$('#cardText').textContent=card.q;$('#flashcard').classList.remove('flipped');$('#setProgress').textContent=`${cardIndex+1} / ${cards.length}`;$('#cardProgress').style.width=`${(cardIndex+1)/cards.length*100}%`}
function flip(){flipped=!flipped;const card=cards[cardIndex];$('#cardSide').textContent=flipped?'ANSWER':'QUESTION';$('#cardText').textContent=flipped?card.a:card.q;$('#flashcard').classList.toggle('flipped',flipped)}
$('#flashcard').addEventListener('click',flip);function move(direction){cardIndex=(cardIndex+direction+cards.length)%cards.length;renderCard()}$('#previousCard').addEventListener('click',()=>move(-1));$('#nextCard').addEventListener('click',()=>move(1));$('#knownCard').addEventListener('click',()=>{known++;move(1)});
$('#modeButton').addEventListener('click',()=>{quizIndex=0;quizScore=0;$('#learn').classList.add('hidden');$('#quiz').classList.remove('hidden');renderQuiz()});$('#backToCards').addEventListener('click',()=>{$('#quiz').classList.add('hidden');$('#learn').classList.remove('hidden')});
function choicesFor(card){const pool=cards.filter(x=>x.a!==card.a).map(x=>x.a).sort(()=>Math.random()-.5).slice(0,3);return [card.a,...pool].sort(()=>Math.random()-.5)}
function renderQuiz(){answered=false;const card=cards[quizIndex],choices=choicesFor(card);$('#quizProgress').textContent=`Question ${quizIndex+1} of ${cards.length}`;$('#quizBar').style.width=`${(quizIndex+1)/cards.length*100}%`;$('#quizQuestion').textContent=card.q;$('#quizFeedback').textContent='';$('#nextQuiz').classList.add('hidden');const box=$('#quizOptions');box.innerHTML='';choices.forEach(choice=>{const b=document.createElement('button');b.textContent=choice;b.addEventListener('click',()=>answer(choice,b,card.a));box.append(b)})}
function answer(choice,button,correct){if(answered)return;answered=true;[...document.querySelectorAll('#quizOptions button')].forEach(b=>{b.disabled=true;if(b.textContent===correct)b.classList.add('correct')});if(choice===correct){quizScore++;$('#quizFeedback').textContent='Correct! ✨'}else{button.classList.add('wrong');$('#quizFeedback').textContent=`Answer: ${correct}`}$('#nextQuiz').classList.remove('hidden')}
$('#nextQuiz').addEventListener('click',()=>{if(quizIndex<cards.length-1){quizIndex++;renderQuiz()}else finish()});
async function finish(){let saved=false;if(user?.id){try{const d=await studyApi('saveResult',{userId:user.id,setId,score:quizScore,total:cards.length,cardsKnown:known});localStorage.setItem('gizmoUser',JSON.stringify(d.user));saved=true}catch{}}$('#quiz').classList.add('hidden');$('#complete').classList.remove('hidden');$('#completeTitle').textContent=`${quizScore} / ${cards.length} correct!`;$('#completeText').textContent=`You marked ${known} cards as known. ${saved?'Your dashboard has been updated.':user?'Could not save — try again later.':'Sign up to save your progress.'}`}
$('#studyAgain').addEventListener('click',()=>{$('#complete').classList.add('hidden');$('#learn').classList.remove('hidden');cardIndex=0;known=0;renderCard()});$('#makeAnother').addEventListener('click',()=>location.reload());document.addEventListener('keydown',e=>{if($('#learn').classList.contains('hidden'))return;if(e.code==='Space'){e.preventDefault();flip()}if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.key.toLowerCase()==='k'){known++;move(1)}});
